spring:
  application:
    name: "server-api"
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://otel-collector:4317

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
    io.opentelemetry: DEBUG
